/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import Aplication.Gimnasio;
import Negocio.clases.Clase;
import Negocio.clases.TipoClase;
import Negocio.usuarios.Cliente;

/**
 *
 * @author Santi
 */
public class VentanaCliente extends javax.swing.JFrame {

    
    Gimnasio controller;
    Cliente clienteIniciado;
    /**
     * Creates new form SoporteTecnico
     * @param controller
     */
    public VentanaCliente(Gimnasio controller, Cliente cliente) {
        this.controller = controller;
        this.clienteIniciado = cliente;
        initComponents();                        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectClase = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        selectTipoClase = new javax.swing.JComboBox<>();
        toggleVirtual = new javax.swing.JToggleButton();
        labelVirtual = new javax.swing.JLabel();
        btnReservarClase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente");

        selectClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectClaseActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de Clase:");

        jLabel2.setText("RESERVAR CLASE");

        jLabel3.setText("Clase:");

        selectTipoClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTipoClaseActionPerformed(evt);
            }
        });

        toggleVirtual.setText("No");
        toggleVirtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleVirtualActionPerformed(evt);
            }
        });

        labelVirtual.setText("Virtual:");

        btnReservarClase.setText("Reservar Clase");
        btnReservarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarClaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectTipoClase, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel1))
                                .addComponent(jLabel2)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(toggleVirtual)
                                    .addComponent(selectClase, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelVirtual)
                        .addGap(290, 290, 290)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addComponent(btnReservarClase, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectTipoClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelVirtual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggleVirtual)
                .addGap(18, 18, 18)
                .addComponent(btnReservarClase, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectClaseActionPerformed
        // TODO add your handling code here:
        // TIENE QUE MOSTRAR LAS CLASES QUE SEAN DEL TIPO ELEGIDO ANTERIORMENTE EN TIPO CLASE        
    }//GEN-LAST:event_selectClaseActionPerformed

    private void selectTipoClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTipoClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectTipoClaseActionPerformed

    private void toggleVirtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleVirtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toggleVirtualActionPerformed

    private void btnReservarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservarClaseActionPerformed

    /**
     * @param args the command line arguments
     */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReservarClase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelVirtual;
    private javax.swing.JComboBox<Clase> selectClase;
    private javax.swing.JComboBox<TipoClase> selectTipoClase;
    private javax.swing.JToggleButton toggleVirtual;
    // End of variables declaration//GEN-END:variables
}
