/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import Aplication.Gimnasio;

/**
 *
 * @author Santi
 */
public class VentanaSoporteTecnico extends javax.swing.JFrame {

    Gimnasio controller;
    /**
     * Creates new form SoporteTecnico
     * @param controller
     */
    public VentanaSoporteTecnico(Gimnasio controller) {
        initComponents();
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearNuevaSede = new javax.swing.JButton();
        btnAdministrarUsuarios = new javax.swing.JButton();
        btnCrearTipoClase = new javax.swing.JButton();
        btnCrearTipoArticulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SoporteTecnico");

        btnCrearNuevaSede.setText("Crear Nueva Sede");
        btnCrearNuevaSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearNuevaSedeActionPerformed(evt);
            }
        });

        btnAdministrarUsuarios.setText("Administrar Usuarios");
        btnAdministrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarUsuariosActionPerformed(evt);
            }
        });

        btnCrearTipoClase.setText("Crear Tipo de Clase");
        btnCrearTipoClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTipoClaseActionPerformed(evt);
            }
        });

        btnCrearTipoArticulo.setText("Crear Tipo de Articulo");
        btnCrearTipoArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTipoArticuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrearTipoArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCrearTipoClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrearNuevaSede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdministrarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnCrearNuevaSede, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdministrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCrearTipoClase, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCrearTipoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearNuevaSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearNuevaSedeActionPerformed
        CrearSede ventanaCrearSede = new CrearSede(this.controller);
        ventanaCrearSede.setLocationRelativeTo(null);
        ventanaCrearSede.setVisible(true);
        
    }//GEN-LAST:event_btnCrearNuevaSedeActionPerformed

    private void btnCrearTipoArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTipoArticuloActionPerformed
        CrearTipoClase ventanaCrearTipoClase = new CrearTipoClase(this.controller);
        ventanaCrearTipoClase.setLocationRelativeTo(null);
        ventanaCrearTipoClase.setVisible(true);
    }//GEN-LAST:event_btnCrearTipoArticuloActionPerformed

    private void btnAdministrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarUsuariosActionPerformed
        AdministrarUsuarios ventanaAdministrarUsuarios = new AdministrarUsuarios(this.controller);
        ventanaAdministrarUsuarios.setLocationRelativeTo(null);
        ventanaAdministrarUsuarios.setVisible(true);
    }//GEN-LAST:event_btnAdministrarUsuariosActionPerformed

    private void btnCrearTipoClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTipoClaseActionPerformed
        CrearTipoArticulo ventanaCrearTipoArticulo = new CrearTipoArticulo(this.controller);
        ventanaCrearTipoArticulo.setLocationRelativeTo(null);
        ventanaCrearTipoArticulo.setVisible(true);
    }//GEN-LAST:event_btnCrearTipoClaseActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrarUsuarios;
    private javax.swing.JButton btnCrearNuevaSede;
    private javax.swing.JButton btnCrearTipoArticulo;
    private javax.swing.JButton btnCrearTipoClase;
    // End of variables declaration//GEN-END:variables
}
