/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import Aplication.Gimnasio;
import Negocio.enums.Nivel;
import Negocio.usuarios.Administrativo;
import java.awt.Component;

/**
 *
 * @author Santi
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Gimnasio controller;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(Gimnasio controller) {
        this.controller = controller;
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSoporteTecnico = new javax.swing.JButton();
        selectAdministrativo = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesion");

        btnSoporteTecnico.setText("Iniciar Sesion Soporte Tecnico");
        btnSoporteTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionSoporteTecnico(evt);
            }
        });

        selectAdministrativo.setInheritsPopupMenu(true);
        for(Administrativo admin : controller.listarAdministrativos()){
            selectAdministrativo.addItem(admin);
        }
        selectAdministrativo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                selectAdministrativoFocusGained(evt);
            }
        });
        selectAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAdministrativoActionPerformed(evt);
            }
        });

        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(selectAdministrativo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSoporteTecnico, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnSoporteTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectAdministrativo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionSoporteTecnico(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionSoporteTecnico
        VentanaSoporteTecnico ventanaSoporteTecnico = new VentanaSoporteTecnico(this.controller);
        ventanaSoporteTecnico.setLocationRelativeTo(null);
        ventanaSoporteTecnico.setVisible(true);        
    }//GEN-LAST:event_btnIniciarSesionSoporteTecnico

    private void selectAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAdministrativoActionPerformed
        
    }//GEN-LAST:event_selectAdministrativoActionPerformed

    private void selectAdministrativoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selectAdministrativoFocusGained
        selectAdministrativo.removeAllItems();
        for(Administrativo admin : controller.listarAdministrativos()){
            selectAdministrativo.addItem(admin);
        }
    }//GEN-LAST:event_selectAdministrativoFocusGained

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jToggleButton1.isSelected()){
            jToggleButton1.setText("Si");
        } else {
            jToggleButton1.setText("No");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Gimnasio controller = new Gimnasio();
                controller.crearAdministrativo("juan", 1);
                controller.crearAdministrativo("juan2", 2);
                controller.crearAdministrativo("juan3", 3);
                controller.crearSede("sede1", Nivel.Platinum, "barrio1", (float) 10);
                controller.agregarSedeAdministrativo(controller.listarAdministrativos().get(0), controller.listarSedes().get(0));
                
                VentanaPrincipal ventanaPrincipal = new VentanaPrincipal(controller);
                ventanaPrincipal.setLocationRelativeTo(null);
                ventanaPrincipal.setVisible(true); 
                
                
            };
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSoporteTecnico;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<Administrativo> selectAdministrativo;
    // End of variables declaration//GEN-END:variables
}
