/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import Aplication.Gimnasio;
import Negocio.enums.Nivel;
import Negocio.usuarios.Administrativo;
import Negocio.usuarios.Cliente;
import java.awt.Component;

/**
 *
 * @author Santi
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Gimnasio controller;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(Gimnasio controller) {
        this.controller = controller;
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSoporteTecnico = new javax.swing.JButton();
        selectAdministrativo = new javax.swing.JComboBox<>();
        btnAdministrativo = new javax.swing.JButton();
        labelDNICliente = new javax.swing.JLabel();
        labelNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtDNICliente = new javax.swing.JTextField();
        btnCliente = new javax.swing.JButton();
        labelTituloIniciarSesionCliente = new javax.swing.JLabel();
        labelTituloIniciarSesionAdministrativo = new javax.swing.JLabel();
        labelTituloIniciarSesionSoporteTecnico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesion");

        btnSoporteTecnico.setText("Iniciar Sesion Soporte Tecnico");
        btnSoporteTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoporteTecnico(evt);
            }
        });

        selectAdministrativo.setInheritsPopupMenu(true);
        for(Administrativo admin : controller.listarAdministrativos()){
            selectAdministrativo.addItem(admin);
        }
        selectAdministrativo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                selectAdministrativoFocusGained(evt);
            }
        });
        selectAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAdministrativoActionPerformed(evt);
            }
        });

        btnAdministrativo.setText("Iniciar Sesion Administrativo");
        btnAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrativo(evt);
            }
        });

        labelDNICliente.setText("DNI:");

        labelNombreCliente.setText("Nombre:");

        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        txtDNICliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIClienteActionPerformed(evt);
            }
        });

        btnCliente.setText("Iniciar Sesion Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliente(evt);
            }
        });

        labelTituloIniciarSesionCliente.setText("INICIAR SESION CLIENTE");

        labelTituloIniciarSesionAdministrativo.setText("INICIAR SESION ADMINISTRATIVO");

        labelTituloIniciarSesionSoporteTecnico.setText("INICIAR SESION SOPORTE TECNICO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNombreCliente)
                    .addComponent(selectAdministrativo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSoporteTecnico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(btnAdministrativo, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(txtNombreCliente)
                    .addComponent(txtDNICliente)
                    .addComponent(labelDNICliente)
                    .addComponent(btnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTituloIniciarSesionSoporteTecnico)
                    .addComponent(labelTituloIniciarSesionAdministrativo)
                    .addComponent(labelTituloIniciarSesionCliente))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelTituloIniciarSesionSoporteTecnico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSoporteTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTituloIniciarSesionAdministrativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectAdministrativo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdministrativo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(labelTituloIniciarSesionCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNombreCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(labelDNICliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDNICliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSoporteTecnico(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoporteTecnico
        VentanaSoporteTecnico ventanaSoporteTecnico = new VentanaSoporteTecnico(this.controller);
        ventanaSoporteTecnico.setLocationRelativeTo(null);
        ventanaSoporteTecnico.setVisible(true);        
    }//GEN-LAST:event_btnSoporteTecnico

    private void selectAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAdministrativoActionPerformed
        
    }//GEN-LAST:event_selectAdministrativoActionPerformed

    private void selectAdministrativoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selectAdministrativoFocusGained
        selectAdministrativo.removeAllItems();
        for(Administrativo admin : controller.listarAdministrativos()){
            selectAdministrativo.addItem(admin);
        }
    }//GEN-LAST:event_selectAdministrativoFocusGained

    private void btnAdministrativo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrativo
        
        // TODO corregir por el administrador elegido correcto
        Administrativo admin = new Administrativo("Admin1", 1);        
        
        VentanaAdministrativo ventanaAdministrativo = new VentanaAdministrativo(this.controller, admin);
        ventanaAdministrativo.setLocationRelativeTo(null);
        ventanaAdministrativo.setVisible(true);
    }//GEN-LAST:event_btnAdministrativo

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void txtDNIClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIClienteActionPerformed

    private void btnCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliente
        // TODO corregir por el cliente elegido correcto (Hay que buscarlo en la lista del controller)
        Cliente cliente = new Cliente("Cliente1", 1, Nivel.Platinum);       
        
        VentanaCliente ventanaCliente = new VentanaCliente(this.controller, cliente);
        ventanaCliente.setLocationRelativeTo(null);
        ventanaCliente.setVisible(true);
    }//GEN-LAST:event_btnCliente

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Gimnasio controller = new Gimnasio();
                controller.crearAdministrativo("juan", 1);
                controller.crearAdministrativo("juan2", 2);
                controller.crearAdministrativo("juan3", 3);
                controller.crearSede("sede1", Nivel.Platinum, "barrio1", (float) 10);
                controller.agregarSedeAdministrativo(controller.listarAdministrativos().get(0), controller.listarSedes().get(0));
                
                VentanaPrincipal ventanaPrincipal = new VentanaPrincipal(controller);
                ventanaPrincipal.setLocationRelativeTo(null);
                ventanaPrincipal.setVisible(true);
                
            };
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrativo;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnSoporteTecnico;
    private javax.swing.JLabel labelDNICliente;
    private javax.swing.JLabel labelNombreCliente;
    private javax.swing.JLabel labelTituloIniciarSesionAdministrativo;
    private javax.swing.JLabel labelTituloIniciarSesionCliente;
    private javax.swing.JLabel labelTituloIniciarSesionSoporteTecnico;
    private javax.swing.JComboBox<Administrativo> selectAdministrativo;
    private javax.swing.JTextField txtDNICliente;
    private javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables
}
